# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punzip < Formula
  desc "punzip, short for parallel-unzip, is a blazing fast concurrent zip extractor."
  homepage "https://github.com/ybirader/pzip"
  version "0.2.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/punzip_Darwin_arm64.tar.gz"
      sha256 "a98ed25e160a3f2872a38f6fc570256942041c0fb0aec620e7af25ae963900e6"

      def install
        bin.install "punzip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/punzip_Darwin_x86_64.tar.gz"
      sha256 "fa767c400ff2a257d24c33031259c47cff811e4698ad7eb9acb271167e836571"

      def install
        bin.install "punzip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/punzip_Linux_arm64.tar.gz"
      sha256 "1227edd18f71cae763d6fb0fce43d82032381fb0fdab28e87e80c65648a60279"

      def install
        bin.install "punzip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/punzip_Linux_x86_64.tar.gz"
      sha256 "6b2eb6d11cb04ada6ac4073ad73274fc8a0b021f46df97a13a3d488859103451"

      def install
        bin.install "punzip"
      end
    end
  end
end
