# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punzip < Formula
  desc "punzip, short for parallel-unzip, is a blazing fast concurrent zip extractor."
  homepage "https://github.com/ybirader/pzip"
  version "0.2.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.2/punzip_Darwin_arm64.tar.gz"
      sha256 "9091355afb339a135ad677b87aa1818040d4731415776a679ea8bb11675017b5"

      def install
        bin.install "punzip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.2/punzip_Darwin_x86_64.tar.gz"
      sha256 "dd2f3e278c5e26e5d008e2d5b5bfecb0753996a17cc28ad4d46513402d11ad7f"

      def install
        bin.install "punzip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.2/punzip_Linux_arm64.tar.gz"
      sha256 "693ed256055f5af43b9b156ceadd9a9ac547608057cd9b81a84823d9ede93431"

      def install
        bin.install "punzip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.2/punzip_Linux_x86_64.tar.gz"
      sha256 "02ca6fe51e8301d60d345cf1bfaa475f4b86830d15a4335250f0766a78ff464a"

      def install
        bin.install "punzip"
      end
    end
  end
end
