# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pzip < Formula
  desc "pzip, short for parallel-zip, is a blazing fast concurrent zip archiver."
  homepage "https://github.com/ybirader/pzip"
  version "0.2.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/pzip_Darwin_x86_64.tar.gz"
      sha256 "4c628b0520b1fbf9029d43019f7202b0272246cd6d59f31644e7e7d5f551e75f"

      def install
        bin.install "pzip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/pzip_Darwin_arm64.tar.gz"
      sha256 "4713de75736f45978395336b6b01d0d29b321cf05526102b00b6339a6ad8ddfd"

      def install
        bin.install "pzip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/pzip_Linux_arm64.tar.gz"
      sha256 "f91e806d963b5f9ce474519205474e79129d17f6d6aff1654bd88797fd09b482"

      def install
        bin.install "pzip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.2.0/pzip_Linux_x86_64.tar.gz"
      sha256 "866673c3191c350819a30f877cddef94473336b46f0164621d0c1ab95880e9b9"

      def install
        bin.install "pzip"
      end
    end
  end
end
