# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pzip < Formula
  desc "pzip, short for parallel-zip, is a blazing fast concurrent zip archiver."
  homepage "https://github.com/ybirader/pzip"
  version "0.1.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.1.1/pzip_Darwin_x86_64.tar.gz"
      sha256 "3ee816cda0e7ed8cb5a4f2ff814ff442503aa1a25291d8e81d64aa82bf4042d4"

      def install
        bin.install "pzip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ybirader/pzip/releases/download/v0.1.1/pzip_Darwin_arm64.tar.gz"
      sha256 "20adb00d0c7acff4abb465a0c866d7c6c18287b51f8d87a6db27d79924e28f8a"

      def install
        bin.install "pzip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ybirader/pzip/releases/download/v0.1.1/pzip_Linux_arm64.tar.gz"
      sha256 "9d8c3ac1397b1d923c4f9dd3d98a053d3e9a69ae0a35f75ef256a4a8e7896127"

      def install
        bin.install "pzip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ybirader/pzip/releases/download/v0.1.1/pzip_Linux_x86_64.tar.gz"
      sha256 "b44ed5fbe9c6cb6198c51c30c6da3de8658c6be38f7d24bfae58dc28746d5850"

      def install
        bin.install "pzip"
      end
    end
  end
end
